steps:
- name: golang:1.22
  entrypoint: /bin/bash
  args:
  - -c
  - apt update && apt install -y zip && bash package.sh ${COMMIT_SHA}
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-blog2-cloud-function-source'
    paths: ['${COMMIT_SHA}.zip']
options:
  logging: CLOUD_LOGGING_ONLY